### ISSUE TITLE
Looking for new owner

### ISSUE THREAD

**Issue by haydenbleasel** [AlexisTM/humans-generator#4]
@AlexisTM?

**Comment by AlexisTM** [comment]
I don't mind to be the owner :D

**Comment by haydenbleasel** [comment]
@AlexisTM Awesome - you'll need to delete your fork first though :)

**Comment by AlexisTM** [comment]
Sorry for this, I never transferred any repo, I thought I had to. (:

**Comment by haydenbleasel** [comment]
@AlexisTM Done - check your email!

**Comment by AlexisTM** [comment]
I am happy to be the new owner!

**Comment by haydenbleasel** [comment]
:)

**Comment by haydenbleasel** [comment]
Hey @AlexisTM I just remembered - I need your NPM username so you can publish updates

**Comment by AlexisTM** [comment]
Hey, indeed, I checked and couldn't publish. My username on npmjs is: alexistm

**Comment by haydenbleasel** [comment]
Done!

**Comment by AlexisTM** [comment]
Thanks!
